INSERT INTO phrase (id, name, author, creativity) VALUES (1, "La vida es o una gran aventura o nada", "Hellen Keller", 0);
INSERT INTO phrase (id, name, author, creativity) VALUES (2, "Si tienes miedo de fallar, probablemente falles", "Kobe Bryant", 0);
INSERT INTO phrase (id, name, author, creativity) VALUES (3, "Pies, ¿para qué os quiero? ¡Si tengo alas para volar!", "Frida Kahlo", 0);
INSERT INTO phrase (id, name, author, creativity) VALUES (4, "Cualquier esfuerzo resulta ligero con el hábito", "Tito Livio", 0);
INSERT INTO phrase (id, name, author, creativity) VALUES (5, "Los campeones siguen jugando hasta que lo hacen bien", "Billie Jean King", 0);
INSERT INTO phrase (id, name, author, creativity) VALUES (6, "No cuentes los días, haz que los días cuenten", "Muhammad Ali", 0);
INSERT INTO phrase (id, name, author, creativity) VALUES (7, "No esperes. Nunca va a ser el momento adecuado", "Napoleon Hill", 0);
INSERT INTO phrase (id, name, author, creativity) VALUES (8, "La vida es una aventura, atrévete", "Teresa de Calcuta", 0);
INSERT INTO phrase (id, name, author, creativity) VALUES (9, "La vida empieza cada cinco minutos", "Andreu Buenafuente", 0);
INSERT INTO phrase (id, name, author, creativity) VALUES (10, "No quiero ganarme la vida, quiero vivir", "Oscar Wilde", 0);
INSERT INTO phrase (id, name, author, creativity) VALUES (11, "Trabaja duro, sé amable y ocurrirán cosas asombrosas", "Conan O'Brien", 0);
INSERT INTO phrase (id, name, author, creativity) VALUES (12, "La vida no examinada no merece la pena ser vivida", "Sócrates", 0);
INSERT INTO phrase (id, name, author, creativity) VALUES (13, "Si no pierdes, no puedes disfrutar de las victorias", "Rafael Nadal", 0);
INSERT INTO phrase (id, name, author, creativity) VALUES (14, "Un día sin una sonrisa es un día perdido", "Charles Chaplin", 0);
INSERT INTO phrase (id, name, author, creativity) VALUES (15, "Piensa, sueña, cree y atrévete", "Walt Disney", 0);
INSERT INTO phrase (id, name, author, creativity) VALUES (16, "Perder el tiempo que disfruto no es tiempo perdido", "Marta Troly", 0);
INSERT INTO phrase (id, name, author, creativity) VALUES (17, "Carpe Diem", "Horacio", 0);
INSERT INTO phrase (id, name, author, creativity) VALUES (18, "Lo que no te mata, te hace más fuerte", "Friedrich Nietzsche", 0);
INSERT INTO phrase (id, name, author, creativity) VALUES (19, "Todas las cosas son imposibles, mientras lo parecen", "Concepción Arenal", 0);
INSERT INTO phrase (id, name, author, creativity) VALUES (20, "Cada momento es especial para quien tiene la visión de reconocerlo como tal", "Henry Miller", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (21, "No se puede encontrar la paz evitando la vida", "Virginia Woolf", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (22, "Lo que haces por ti se desvanece cuando mueres. Lo que haces por el resto conforma tu legado", "Kalu Ndukwe Kalu", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (23, "Buenos amigos, buenos libros y tener una conciencia tranquila: esta es la vida ideal", "Mark Twain", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (24, "Cuando las oportunidades no llamen a tu puerta, construye una", "Milton Berle", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (25, "La vida es un viaje de autodescubrimiento, atrévete a explorar", "Anaïs Nin", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (26, "Al cabo de los años he observado que la belleza, como la felicidad, es frecuente. No pasa un día en que no estemos, un instante, en el paraíso", "Jorge Luis Borges", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (27, "La risa es el Sol que ahuyenta el invierno del rostro humano", "Victor Hugo", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (28, "La felicidad es amor, no otra cosa. El que sabe amar es feliz", "Hermann Hesse", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (29, "El futuro pertenece a quienes creen en la belleza de sus sueños", "Eleanor Roosevelt", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (30, "Un día sin reír es un día perdido", "Charles Chaplin", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (31, "La vida es como el jazz… es mucho mejor si es improvisada", "George Gershwin", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (32, "La vida es la constante sorpresa de saber que existo", "R. Tagore", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (33, "Los sabios son los que buscan la sabiduría los necios piensan haberla encontrado", "Napoleón", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (34, "No lastimes a los demás con lo que te causa dolor a ti mismo", "Buda", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (35, "Recuerda que la felicidad no depende de quién eres o qué tienes depende únicamente de lo que piensas", "Dale Carnegie", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (36, "Un hombre que no se alimenta de sus sueños envejece pronto", "William Shakespeare", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (37, "El pesimista se queja del viento el optimista espera que cambie el realista ajusta las velas", "William George Ward", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (38, "Cuando las cosas se ponen difíciles, lo duro es ponerse en marcha", "Joseph Kennedy", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (39, "La vida no es justa, es apenas más justa que la muerte, eso es todo", "William Goldman", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (40, "Amar y sufrir es, a la larga, la única forma de vivir con plenitud y dignidad", "Gregorio Marañón", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (41, "La vida no es siempre una cuestión de tener buenas cartas, sino, a veces, de jugar bien una mala mano", "Jack London", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (42, "Es curioso que la vida, cuanto más vacía, más pesa", "León Daudí", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (43, "Me entenderás… cuando te duela el alma como a mí", "Frida Kahlo", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (44, "La vida no es sino una continua sucesión de oportunidades para sobrevivir", "Gabriel García Márquez", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (45, "Si el hombre no ha descubierto nada por lo que morir, no es digno de vivir", "Martin Luther King", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (46, "La experiencia no es lo que te ocurre, es lo que haces con lo que te ocurre", "Aldous Huxley", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (47, "La vida no va de encontrarse a uno mismo, sino de crearse a uno mismo", "George Bernard Shaw", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (48, "En la vida hay algo peor que el fracaso: el no haber intentado nada", "Franklin D. Roosvelt", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (49, "La peor lucha es la que no se hace", "Karl Marx", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (51, "Aquellos que no se mueven no notan sus cadenas", "Rosa Luxemburgo", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (52, "Deja de pensar en la vida y resuélvete a vivirla", "Paulo Coelho", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (53, "No hay lugar donde ir salvo a cualquier parte, así que sigue caminando", "Jack Kerouac", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (54, "Saber lo que hay que hacer elimina el miedo", "Rosa Parks", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (55, "Sólo aquellos que se arriesgan a caer pueden conseguir grandes cosas", "Robert F. Kennedy", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (56, "El éxito no es el final, el fracaso no es fatal: es el coraje por seguir lo que cuenta", "Winston S. Churchill", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (57, "La vida es como una bicicleta: si quieres mantener el equilibrio, pedalea hacia delante", "Albert Einstein", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (58, "Convierte siempre una situación negativa en una positiva", "Michael Jordan", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (59, "Aprendí que no se puede dar marcha atrás, que la esencia de la vida es ir hacia adelante", "Agatha Christie", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (60, "Un sólo pensamiento positivo por la mañana puede iluminar todo un día", "Dalai Lama", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (61, "Con el nuevo día llega nueva fuerza y nuevos pensamientos", "Eleanor Roosevelt", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (62, "Todos tus sueños se harán realidad si tienes el coraje de perseguirlos", "Walt Disney", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (63, "Deja marcado en tu corazón que cada día es el mejor día del año", "Ralph Waldo Emerson", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (64, "Que no te avergüencen tus fracasos. Aprende de ellos y vuelve a empezar", "Richard Branson", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (65, "Recuerda que sólo porque tocaste fondo, no significa que tengas que quedarte allí", "Robert Downey Jr", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (66, "La única diferencia entre el éxito y el fracaso es la capacidad de actuar", "Alexander Graham Bell", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (67, "Si puedes cambiar tu mente, puedes cambiar el mundo", "William James", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (68, "El fracaso es la oportunidad de comenzar de nuevo con más inteligencia", "Henry Ford", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (69, "El sentido común no es resultado de la educación", "Victor Hugo", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (70, "La educación es el arte de hacer visibles las cosas invisibles", "Jean-François Lyotard", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (71, "No todos los lectores son líderes, pero todos los lectores se convierten en líderes", "Harry S. Truman", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (72, "Quien se atreve a enseñar, nunca debe dejar de aprender", "John Cotton Dana", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (73, "Por la ignorancia nos equivocamos, y por las equivocaciones aprendemos", "Proverbio romano", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (74, "La educación es el vestido de gala para asistir a la fiesta de la vida", "Miguel Rojas Sánchez", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (75, "La educación es el acto de despertar la curiosidad de la mente y alimentarla", "Bob Dylan", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (76, "La educación es el cimiento sobre el cual construimos nuestro futuro", "Christine Gregoire", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (77, "A menudo damos a los niños respuestas que recordar en lugar de problemas a resolver", "Roger Lewin", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (78, "La educación es el proceso en el que descubrimos que, aprendiendo, aprendemos a aprender", "José Saramago", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (79, "La mejor arma contra la ignorancia es el estudio", "Rafael Escandón", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (80, "La educación no es preparación para la vida la educación es la vida en sí misma", "John Dewey", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (81, "Sé tu mismo", "Lao Tzu", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (82, "Pensar es fácil, actuar es difícil, y poner los pensamientos de uno mismo en acción es lo más difícil del mundo", "Goethe", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (83, "Debes de estar dispuesto a ser un principiante cada una de tus mañanas", "Meister Eckhart", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (84, "La enseñanza que deja huella no es la que se hace de cabeza a cabeza, sino de corazón a corazón", "Howard G. Hendricks", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (85, "Verás, hasta que te conocí, sólo había experimentado el deseo. El amor, nunca", "Pierre Choderlos de Laclos", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (86, "Educar la mente sin educar el corazón no es educación en absoluto", "Aristóteles", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (87, "Te quiero no por quien eres, sino por quien soy cuando estoy contigo", "Gabriel García Márquez", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (88, "La educación es el único camino para escapar de la esclavitud mental", "Frederick Douglass", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (89, "El amor no tiene cura, pero es la única cura para todos los males", "Leonard Cohen", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (90, "Un niño con falta de educación es un niño perdido", "John F. Kennedy", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (91, "Escoge una persona que te mire como si fueses magia", "Frida Kahlo", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (92, "Un ser humano no alcanza sus cotas más altas hasta que está educado", "Horace Mann", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (93, "Temer al amor es temer a la vida, y los que temen a la vida ya están medio muertos", "Bertrand Russell", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (94, "La educación genera confianza. La confianza genera esperanza. La esperanza genera paz", "Confucio", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (95, "Sabes que estás enamorado cuando no quieres acostarte porque la realidad es por fin mejor que tus sueños", "Dr. Seuss", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (96, "Antes de hablar, piensa pero antes de pensar, lee", "Frances Ann Lebowitz", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (97, "Yo me enamoré de sus demonios. Ella, de mi oscuridad. Éramos el infierno perfecto", "Mario Benedetti", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (98, "La sabiduría no es producto de la escolarización, sino de un intento a lo largo de la vida de adquirirlo", "Albert Einstein", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (99, "El amor es el deseo de encontrar a la mitad perdida de nosotros mismos", "Milan Kundera", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (100, "El estudio sin deseo estropea la memoria y no retiene nada de lo que toma", "Leonardo da Vinci", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (101, "La raíz de todas las pasiones es el amor. De él nace la tristeza, el gozo, la alegría y la desesperación", "Lope de Vega", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (102, "La vida debe ser una incesante educación", "Gustave Flaubert", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (103, "El amor es invisible y entra y sale por donde quiere sin que nadie le pida cuenta de sus hechos", "Miguel de Cervantes", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (104, "El conocimiento te dará la oportunidad de marcar una diferencia", "Claire Fagin", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (105, "Hay amores tan bellos que justifican todas las locuras que hacen cometer", "Plutarco", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (106, "Toda vida es una constante educación", "Eleanor Roosevelt", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (107, "Ni la ausencia ni el tiempo son nada cuando se ama", "Alfred de Musset", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (108, "Las plantas las endereza el cultivo a los hombres, la educación", "J.J. Rousseau", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (109, "El amor es como la música, la pintura, los libros… no se busca, se encuentra", "Miguel de Cervantes", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (110, "La clave de la educación no es enseñar, es despertar", "Ernest Renan", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (111, "El amor de los jóvenes en verdad no está en su corazón, sino más bien en sus ojos", "William Shakespeare", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (112, "Hay besos que en los labios dejan huellas como un campo de sol entre dos hielos", "Gabriela Mistral", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (113, "El amor es mejor maestro que el deber", "Albert Einstein", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (114, "El amor es la alegría de los buenos, la reflexión de los sabios, el asombro de los incrédulos", "Platón", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (115, "El amor, por no tener geografía, no conoce límites", "Truman Capote", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (116, "Lo que se hace por amor está más allá del bien y del mal", "Friedrich Nietzsche", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (117, "El amor es una flor que debes dejar crecer", "John Lennon", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (118, "Si tuviera que volver a comenzar mi vida, intentaría encontrarte mucho antes", "Antoine de Saint-Exupéry", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (119, "El crimen del amor es el olvido", "Maurice Chevalier", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (120, "La vida es la flor de la que el amor es la miel", "Victor Hugo", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (121, "Enseñar es aprender dos veces", "Joseph Joubert", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (122, "La educación es el arma más poderosa que puedes usar para cambiar el mundo", "Nelson Mandela", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (123, "Los niños tienen que ser enseñados sobre cómo pensar, no qué pensar", "Margaret Mead", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (124, "Vivir sin filosofar es, propiamente, tener los ojos cerrados, sin tratar de abrirlos jamás", "René Descartes", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (125, "Una inversión en conocimiento paga el mejor interés", "Benjamin Franklin", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (126, "Amamos porque esa es la única gran aventura", "Nikki Giovanni", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (127, "El amor es la poesía de los sentidos", "Honoré de Balzac", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (128, "La medida del amor es amar sin medida", "San Agustín", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (129, "Amar no es mirarse el uno al otro es mirar juntos en la misma dirección", "Antoine de Saint-Exupéry", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (130, "Quiero llenar mi boca con tu nombre", "Pablo Neruda", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (131, "El amor conquista todas las cosas. Démosle paso al amor", "Virgilio", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (132, "El amor intenso no mide, sino que simplemente da", "Teresa de Calcuta", 1);
INSERT INTO phrase (id, name, author, creativity) VALUES (133, "Si no tardas mucho, te espero toda la vida", "Oscar Wilde", 1);
INSERT INTO history (id, name, createdAt, errorMessage, phraseId) VALUES (15, "carpe2", "2024-10-29 15:37:24", "No he encontrado una frase con esa palabra", 11);
INSERT INTO history (id, name, createdAt, errorMessage, phraseId) VALUES (17, "carpe", "2024-10-29 16:11:36", "", 17);
INSERT INTO history (id, name, createdAt, errorMessage, phraseId) VALUES (18, "carpe4", "2024-10-29 16:13:52", "No he encontrado una frase con esa palabra", 12);
INSERT INTO history (id, name, createdAt, errorMessage, phraseId) VALUES (19, "vida", "2024-10-29 16:31:14", "", 120);
INSERT INTO history (id, name, createdAt, errorMessage, phraseId) VALUES (20, "vida", "2024-10-29 16:31:20", "", 42);
INSERT INTO history (id, name, createdAt, errorMessage, phraseId) VALUES (21, "sonrisa", "2024-10-29 16:42:40", "No he encontrado una frase con esa palabra", 82);
INSERT INTO history (id, name, createdAt, errorMessage, phraseId) VALUES (22, "sonrisa", "2024-10-29 16:42:45", "", 14);
INSERT INTO history (id, name, createdAt, errorMessage, phraseId) VALUES (23, "risas", "2024-10-29 16:42:51", "No he encontrado una frase con esa palabra", 19);
INSERT INTO history (id, name, createdAt, errorMessage, phraseId) VALUES (24, "risas", "2024-10-29 16:42:53", "No he encontrado una frase con esa palabra", 128);
INSERT INTO history (id, name, createdAt, errorMessage, phraseId) VALUES (25, "amor", "2024-10-29 16:43:02", "No he encontrado una frase con ese límite", 63);
INSERT INTO history (id, name, createdAt, errorMessage, phraseId) VALUES (26, "amor", "2024-10-29 16:43:08", "No he encontrado una frase con esa palabra", 17);
INSERT INTO history (id, name, createdAt, errorMessage, phraseId) VALUES (27, "amor", "2024-10-29 16:43:15", "", 120);
INSERT INTO history (id, name, createdAt, errorMessage, phraseId) VALUES (28, "cosas", "2024-10-29 16:43:25", "", 131);
INSERT INTO history (id, name, createdAt, errorMessage, phraseId) VALUES (29, "flor", "2024-10-29 16:43:28", "", 120);
INSERT INTO history (id, name, createdAt, errorMessage, phraseId) VALUES (30, "vida", "2024-12-03 17:19:44", "", 9);
INSERT INTO history (id, name, createdAt, errorMessage, phraseId) VALUES (31,"empi","2024-12-05 17:03:34","No he encontrado una frase con esa palabra",2);
INSERT INTO history (id,name ,createdAt,errorMessage ,phraseId) VALUES(32,"empieza","2024-12-05 17:03:37","","9");
INSERT INTO history (id,name ,createdAt,errorMessage ,phraseId) VALUES(33,"vida","2024-12-05 17:26:04","","1");
INSERT INTO history (id,name ,createdAt,errorMessage ,phraseId) VALUES(39,"vida","2024-12-05 17:27:11","","12");
INSERT INTO history (id,name ,createdAt,errorMessage ,phraseId) VALUES(41,"vida","2024-12-05 17:32:19","","12");
INSERT INTO history (id,name ,createdAt,errorMessage ,phraseId) VALUES(42,"carpe","2024-12-05 17:41:10","No he encontrado una frase con esa palabra ",3);
INSERT INTO history (id,name ,createdAt,errorMessage ,phraseId) VALUES(44,"carpe","2024-12-05 17:41:23","No he encontrado una frase con esa palabra ",8);
INSERT INTO history (id,name ,createdAt,errorMessage ,phraseId) VALUES(45,"diem","2024-12-05 17:41:34","No he encontrado una frase con esa palabra ",11);
INSERT INTO history (id,name ,createdAt,errorMessage ,phraseId) VALUES(47,"Diem","2024-12-05 17:42:26","No he encontrado una frase con esa palabra ",69);
INSERT INTO history (id,name ,createdAt,errorMessage ,phraseId) VALUES(50,"cuentes","2024-12-05 17:44:15","","6");
INSERT INTO history (id,name ,createdAt,errorMessage ,phraseId) VALUES(51,"amigos","2024-12-05 17:44:25","No he encontrado una frase con esa palabra ",19);
INSERT INTO history (id,name ,createdAt,errorMessage ,phraseId) VALUES(52,"amigos","2024-12-05 17:44:36","","23");